# Generated by Django 4.1.4 on 2023-01-12 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_extenduser_user'),
        ('references', '0002_remove_flowfunds_date_remove_storageoperation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_contracts', to='contacts.organization'),
        ),
    ]
