# Generated by Django 4.1.4 on 2022-12-13 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('temps', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('Document', models.CharField(max_length=255)),
                ('formalized', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_contracts', to='contacts.extenduser')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='temps.status')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(max_length=30, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_article', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StorageOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_operation', models.CharField(max_length=30, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_operations', to='temps.operationtype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_operations', to='orders.purchaseorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='references.storage')),
            ],
        ),
        migrations.CreateModel(
            name='FlowFunds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('currency', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=255)),
                ('came_from', models.CharField(max_length=30)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='references.contract')),
            ],
            options={
                'unique_together': {('number', 'contract')},
            },
        ),
    ]
