# Generated by Django 4.1.4 on 2022-12-15 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowfunds',
            name='date',
        ),
        migrations.RemoveField(
            model_name='storageoperation',
            name='date',
        ),
        migrations.AddField(
            model_name='flowfunds',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storageoperation',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='formalized',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
