# Generated by Django 4.1.4 on 2022-12-13 20:57

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('temps', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sex', models.CharField(max_length=1)),
                ('birthday', models.DateField()),
                ('Number', models.CharField(max_length=11)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extend_users', to='temps.position')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_number', models.CharField(max_length=30, unique=True)),
                ('bank_name', models.CharField(max_length=255)),
                ('bic', models.CharField(max_length=30)),
                ('corres_number', models.CharField(max_length=30)),
                ('legal_address', models.CharField(max_length=255)),
                ('mail_address', models.CharField(max_length=255)),
                ('inn', models.CharField(max_length=21)),
                ('kpp', models.CharField(max_length=21)),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='contacts.extenduser')),
            ],
        ),
    ]
