# Generated by Django 4.1.4 on 2022-12-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='is_booker',
            field=models.BooleanField(default=False),
        ),
    ]
