# Generated by Django 4.1.4 on 2022-12-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_extenduser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='full_name',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='short_name',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='bank_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('full_name', 'short_name', 'bank_number')},
        ),
    ]
