# Generated by Django 4.1.4 on 2023-01-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_extenduser_middle_name_organization_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extenduser',
            name='user',
        ),
    ]
