# Generated by Django 4.1.4 on 2023-01-12 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0005_remove_extenduser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='extended_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
