# Generated by Django 4.1.4 on 2022-12-15 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, unique=True)),
                ('order_reg_date', models.DateField(auto_now_add=True)),
                ('date_arrival', models.DateField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('vat', models.IntegerField()),
                ('summary', models.CharField(max_length=255)),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_orders', to='contacts.extenduser')),
            ],
        ),
    ]
