# Generated by Django 4.1.4 on 2022-12-13 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('references', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='contract_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_orders', to='references.contract'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='contacts.organization'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_orders', to='contacts.extenduser'),
        ),
    ]
